CREATE TABLE EAGER_API_DEPENDENCY (
  EAGER_DEPENDENCY_NAME VARCHAR(200) NOT NULL,
  EAGER_DEPENDENCY_VERSION VARCHAR(30) NOT NULL,
  EAGER_DEPENDENT_NAME VARCHAR(200) NOT NULL,
  EAGER_DEPENDENT_VERSION VARCHAR(30) NOT NULL,
  EAGER_DEPENDENCY_OPERATIONS VARCHAR(200)
)ENGINE INNODB;